"""empty message

Revision ID: abb0270303d1
Revises: 1bf488d9b86d
Create Date: 2025-08-24 18:58:26.051484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb0270303d1'
down_revision = '1bf488d9b86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('mass', sa.String(), nullable=True),
    sa.Column('skin_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('rotation_period', sa.String(), nullable=True),
    sa.Column('orbital_period', sa.String(), nullable=True),
    sa.Column('gravity', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('climate', sa.String(), nullable=True),
    sa.Column('terrain', sa.String(), nullable=True),
    sa.Column('surface_water', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.String(), nullable=True),
    sa.Column('crew', sa.String(), nullable=True),
    sa.Column('passengers', sa.String(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(), nullable=True),
    sa.Column('cargo_capacity', sa.String(), nullable=True),
    sa.Column('consumables', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_character',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('favorite_planet',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.create_table('favorite_vehicle',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vehicle_id')
    )
    op.drop_table('Planets')
    op.drop_table('Vehicles')
    op.drop_table('Characters')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    op.create_table('Characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mass', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('skin_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Characters_pkey')
    )
    op.create_table('Vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicle_class', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cost_in_credits', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('crew', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_atmosphering_speed', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cargo_capacity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('consumables', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Vehicles_pkey')
    )
    op.create_table('Planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rotation_period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('orbital_period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('population', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surface_water', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('residents', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['diameter'], ['user.id'], name='Planets_diameter_fkey'),
    sa.PrimaryKeyConstraint('id', name='Planets_pkey')
    )
    op.drop_table('favorite_vehicle')
    op.drop_table('favorite_planet')
    op.drop_table('favorite_character')
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
